### ISSUE TITLE
Error running client:EmptyDataError: call to getMinimumGracePeriod() unexpectedly returned no data

### ISSUE THREAD

**Issue by whatisgravity** [pipermerriam/ethereum-alarm-clock#53]
I installed it from pip, there were no apparent errors. It just fails to start.

    Exception in thread Thread-3:
    Traceback (most recent call last):
    File "/usr/lib/python2.7/threading.py", line 810, in bootstrap_inner
    self.run()
    File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(self.__args, *self.__kwargs)
    File "/home/user/alarm-0.6.0/env/local/lib/python2.7/site-packages/eth_alarm_client/scheduler.py", line 70, in monitor
    self.schedule_calls()
    File "/home/user/alarm-0.6.0/env/local/lib/python2.7/site-packages/eth_alarm_client/scheduler.py", line 178, in schedule_calls
    max(0, self.block_sage.current_block_number - self.minimum_grace_period),
    File "/home/user/alarm-0.6.0/env/local/lib/python2.7/site-packages/eth_alarm_client/utils.py", line 22, in __get
    res = instance.dict[self.name] = self.func(instance)
    File "/home/user/alarm-0.6.0/env/local/lib/python2.7/site-packages/eth_alarm_client/scheduler.py", line 57, in minimum_grace_period
    return self.scheduler.getMinimumGracePeriod()
    File "/home/user/alarm-0.6.0/env/local/lib/python2.7/site-packages/populus/contracts/functions.py", line 57, in call
    return self.call(args, *kwargs)
    File "/home/user/alarm-0.6.0/env/local/lib/python2.7/site-packages/populus/contracts/functions.py", line 91, in call
    return self.cast_return_data(output)
    File "/home/user/alarm-0.6.0/env/local/lib/python2.7/site-packages/populus/contracts/common.py", line 80, in cast_return_data
    raise EmptyDataError("call to {0} unexpectedly returned no data".format(self))
    EmptyDataError: call to getMinimumGracePeriod() unexpectedly returned no data

**Comment by whatisgravity** [comment]
I get it when I add either

    --client rpc

or

    --adddress (some address)

These parameters were in the documentation.

**Comment by whatisgravity** [comment]
I can confirm I have a version I installed last night on a differement machine with the same OS works. I believe it was a recent change made.

**Comment by pipermerriam** [comment]
* What version of `ethereum-alarm-clock-client` is installed?
* Was `eth_alarm` invoked with the `--address` parameter (if so what address)?
* Are you running against the main-net or the test-net?

This error comes from calling a function on either a non-existent contract, or a contract which does not have that function (wrong contract or wrong version of the contract).

**Comment by whatisgravity** [comment]
1. Version 0.6.0
2. Yes, the address was the address I created and supplied the password for when opening geth. Was this supposed to be the contract address? From inspecting the example on the blockchain it appeared to be your personal address and not the contract address.
3. Main-net I believe, I'm not specifying test net anywhere.

**Comment by pipermerriam** [comment]
Ok, you can remove the `--address` parameter.  It's meant to specify the address of the alarm service (but if you leave it off it will default to `0xe109ecb193841af9da3110c80fdd365d1c23be2a`

Please re-open if this doesn't fix your issue.

**Comment by pipermerriam** [comment]
In addition, the latest version of the client is 0.7.3

https://pypi.python.org/pypi/ethereum-alarm-clock-client

You should be able to see what version of the alarm clock client is installed with `pip freeze | grep ethereum-alarm-clock-client`

**Comment by whatisgravity** [comment]
That resolved all my confusion. Thank you for your time.

**Comment by whatisgravity** [comment]
Is --client rpc also the default value and unnecessary?

**Comment by pipermerriam** [comment]
Quite possibly.  I think this is a leftover to when I was trying to switch
over to using the IPC (socket) interface and I didn't remove it from my
notes.

**Comment by whatisgravity** [comment]
For myself and others who run into this problem, ensure you have the entire blockchain downloaded before starting eth_alarm. You will get the above error if you do not.
