### ISSUE TITLE
Failure to start due to assets/v0.8.0.json not found (fix known)

### ISSUE THREAD

**Issue by veox** [pipermerriam/ethereum-alarm-clock#74]
Having applied (local) fixes for #72 and #73, `sudo supervisord start scheduler-v8` fails with ([full trace](https://gist.github.com/veox/2e531c2e16067c9dbdb9dfc9b5fec494)):

``` python
/home/eac/opt/eac-client-8.0.0b1/env/lib/python3.5/site-packages/dotenv/main.py:24:
    UserWarning: Not loading .env - it doesn't exist.
...
  File "/home/eac/opt/eac-client-8.0.0b1/env/lib/python3.5/site-packages/alarm_client/config.py", line 195, in compiled_assets
    with open(self.compiled_assets_path) as assets_file:
FileNotFoundError: [Errno 2] No such file or directory:
    '/home/eac/opt/eac-client-8.0.0b1/env/lib/python3.5/site-packages/alarm_client/assets/v0.8.0.json'
```

**Comment by veox** [comment]
`MANIFEST.in` has

`include alarm_client/assets/v8.0.0.json`

but the file is called `alarm_client/assets/v0.8.0.json` in the tree.

The file describes the ABI of EAC contracts, so it should probably have `v0.8.0` in the name (version of EAC), not `v8.0.0` (version of the client, as seen on [PyPI](https://pypi.python.org/pypi/ethereum-alarm-clock-client/8.0.0b1).

[Release versioning](https://github.com/pipermerriam/ethereum-alarm-clock/releases) seems a bit confusing to me, and it's possible that the [v8.0.0b1](https://github.com/pipermerriam/ethereum-alarm-clock/releases/tag/v8.0.0b1) tag was a typo in itself, and should have been `v0.8.0b1`.

To launch with currently deployed version of EAC (`0.7.0`), a different JSON should probably be written up.

**Comment by veox** [comment]
Providing the testnet (Morden?) `assets/v0.8.0.json` to a mainnet EAC client (with `scheduler_password` file present, but having bogus contents) allows the client to start.

It then exits by means of several unhandled exceptions ([`scheduler-v8.stderr.log` file](https://gist.github.com/veox/a4bbdb2c36cdeb9b252b087f46a85271)), all pertaining to `pylru`. `scheduler-v8.stdout.log` contains eight lines of

```
Starting client
```

I hope this failure is due to one of the changes in the first paragraph, and not an incompatibility in `pylru`.

**Comment by pipermerriam** [comment]
I had weird issues at one point with getting pylru to install.  Don't remember any specifics beyond that it appeared to be installed but was not importable (or something like that)

**Comment by Pavangupta98** [comment]
What's wrong with this ?

>>> from web3 import Web3, HTTPProvider, IPCProvider
>>> web3 = Web3(HTTPProvider('http://localhost:8545'))
>>> web3 = Web3(IPCProvider('/root/home/pavan/.ethereum/geth.ipc'))
>>> web3.eth.blockNumber
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/.venv-py3/lib/python3.5/site-packages/web3-4.0.0b4-py3.5.egg/web3/eth.py", line 82, in blockNumber
    return self.web3.manager.request_blocking("eth_blockNumber", [])
  File "/root/.venv-py3/lib/python3.5/site-packages/web3-4.0.0b4-py3.5.egg/web3/manager.py", line 96, in request_blocking
    response = self._make_request(method, params)
  File "/root/.venv-py3/lib/python3.5/site-packages/web3-4.0.0b4-py3.5.egg/web3/manager.py", line 79, in _make_request
    return request_func(method, params)
  File "/root/.venv-py3/lib/python3.5/site-packages/web3-4.0.0b4-py3.5.egg/web3/middleware/formatting.py", line 23, in middleware
    response = make_request(method, params)
  File "/root/.venv-py3/lib/python3.5/site-packages/web3-4.0.0b4-py3.5.egg/web3/middleware/attrdict.py", line 20, in middleware
    response = make_request(method, params)
  File "/root/.venv-py3/lib/python3.5/site-packages/web3-4.0.0b4-py3.5.egg/web3/middleware/formatting.py", line 23, in middleware
    response = make_request(method, params)
  File "/root/.venv-py3/lib/python3.5/site-packages/web3-4.0.0b4-py3.5.egg/web3/middleware/formatting.py", line 23, in middleware
    response = make_request(method, params)
  File "/root/.venv-py3/lib/python3.5/site-packages/web3-4.0.0b4-py3.5.egg/web3/providers/ipc.py", line 152, in make_request
    with self._lock, self._socket as sock:
  File "/root/.venv-py3/lib/python3.5/site-packages/web3-4.0.0b4-py3.5.egg/web3/providers/ipc.py", line 42, in __enter__
    self.sock = self._open()
  File "/root/.venv-py3/lib/python3.5/site-packages/web3-4.0.0b4-py3.5.egg/web3/providers/ipc.py", line 55, in _open
    return get_ipc_socket(self.ipc_path)
  File "/root/.venv-py3/lib/python3.5/site-packages/web3-4.0.0b4-py3.5.egg/web3/providers/ipc.py", line 26, in get_ipc_socket
    sock.connect(ipc_path)
FileNotFoundError: [Errno 2] No such file or directory

**Comment by veox** [comment]
A few things:

* it seems unrelated to the issue;
* you're setting `web3` to use `HTTPProvider`, and then immediately re-setting to use `IPCProvider`;
* the error is due to there being no socket at the indicated location.

**Comment by pipermerriam** [comment]
The current code in this repo isn't supported or expected to work.  Revamp of the service is underway.  Stay tuned.  No set timeline.
