### ISSUE TITLE
Running tests requires alarm_client to be installed

### ISSUE THREAD

**Issue by veox** [pipermerriam/ethereum-alarm-clock#79]
The readme suggests that running

``` sh
git clone 'https://github.com/pipermerriam/ethereum-alarm-clock.git'
cd ethereum-alarm-clock
virtualenv .env && source .env/bin/activate
pip install populus
py.test tests/ # make test
```

would start with executing the test suite. However, doing that results in

``` python
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/_pytest/config.py", line 325, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('/home/veox/src/ethereum-alarm-clock/tests')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/_pytest/config.py", line 356, in _importconftest
    return self._conftestpath2mod[conftestpath]
KeyError: local('/home/veox/src/ethereum-alarm-clock/tests/conftest.py')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/_pytest/config.py", line 362, in _importconftest
    mod = conftestpath.pyimport()
  File "/usr/lib/python3.6/site-packages/py/_path/local.py", line 662, in pyimport
    __import__(modname)
  File "/usr/lib/python3.6/site-packages/_pytest/assertion/rewrite.py", line 216, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "/home/veox/src/ethereum-alarm-clock/tests/conftest.py", line 14, in <module>
    from alarm_client.contracts.transaction_request import TransactionRequestFactory
ModuleNotFoundError: No module named 'alarm_client'
ERROR: could not load /home/veox/src/ethereum-alarm-clock/tests/conftest.py
```

In other words, `conftest.py` requires the `ethereum-alarm-clock-client` package to be available, which provides the `alarm_client` module.

Maybe it should use the local copy instead?..

**Comment by pipermerriam** [comment]
toss a `pip install -e .` into your commands and it should work.  That will work from a local copy like you want but get all the python `PATH` bits working as expected.

**Comment by veox** [comment]
Ah, and I suppose `.env` isn't supposed to be the virtualenv path either. :)

**Comment by pipermerriam** [comment]
Yeah, `.env` is meant to be in the root of wherever you're running the client from.
